# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
  - 'on': [ 'Linux']
    'require':
      'frameworks/extra-cmake-modules': '@latest'

Options:
  require-passing-tests-on: [ '@all' ]
