#!/bin/sh

cd `dirname $0`

export SCRIPTDIR=$PWD
export BUILDDIR=$PWD/build

echo "Building Kst from $SCRIPTDIR into $BUILDDIR"

if [ "$1" = "release" ]
then
  echo "Building in Release mode"
  export KST_DEBUG_MODE=0
else
  echo "Building in Debug mode"
  export KST_DEBUG_MODE=1
fi

if [ "$2" ]
then
  echo "Output directory of $2 has been requested"
  export OUTPUT_DIR=$2
fi

mkdir -p $BUILDDIR
cd $BUILDDIR
qmake -r $SCRIPTDIR/kst.pro
#qmake-qt4 $SCRIPTDIR/kst.pro -r -spec linux-g++

make -j3
#make -j 3 -w 

