#ifndef KSTCONFIG_H
#define KSTCONFIG_H

/* config.h.  Generated by cmake from config.h.cmake */

#define KSTVERSION "${KST_VERSION}"

/* Define if you have unsetenv */
#cmakedefine HAVE_UNSETENV 1

#endif

