#!/bin/sh

cd `dirname $0`

export SCRIPTDIR=$PWD
export BUILDDIR=$PWD/build

echo "Building Kst from $SCRIPTDIR into $BUILDDIR"

if [ "$1" = "debug" ]
then
  echo "Building in Debug mode"
  export KST_DEBUG_MODE=1
else
  echo "Building in Release mode"
  export KST_DEBUG_MODE=0
fi

if [ "$2" ]
then
  echo "Installation location of $2 has been requested"
  export INSTALL_PREFIX=$2
fi

if [ "$3" ]
then
  echo "Installation library directory of $3 has been requested"
  export INSTALL_LIBDIR=$3
fi

if [ "$4" ]
then
  echo "Output directory of $4 has been requested"
  export OUTPUT_DIR=$4
fi

if [ "$INSTALL_LIBDIR" ]
then
  echo "Build will be automatically installed to the the configured location ($INSTALL_PREFIX)"
else
  echo "Build will be automatically install to the default location (/usr)"
fi

mkdir -p $BUILDDIR
cd $BUILDDIR
qmake -r $SCRIPTDIR/kst.pro

if [ -d /opt/icecream/bin ]
then
	echo "Using Icecream"
	PATH=/opt/icecream/bin:$PATH make -j4
	PATH=/opt/icecream/bin:$PATH make install
else
	make -j3
	make install
fi
