
include(FindPkgConfig)

pkg_check_modules(GSL QUIET)

if(NOT GSL_INCLUDEDIR AND NOT GSL_LIBRARIES)
	set(GSL_INCLUDEDIR GSL_INCLUDEDIR-NOTFOUND CACHE STRING "" FORCE)
	FIND_PATH(GSL_INCLUDEDIR gsl_version.h
		HINTS
		ENV GSL_DIR
		PATH_SUFFIXES include/gsl include
		PATHS
		)
	FIND_LIBRARY(GSL_LIBRARY_C gsl 
		HINTS
		ENV GSL_DIR
		PATH_SUFFIXES lib
		PATHS
		)
endif()

#message(STATUS "GSL: ${GSL_INCLUDEDIR}")
#message(STATUS "GSL: ${GSL_LIBRARY}")
IF(GSL_INCLUDEDIR AND GSL_LIBRARY)
	MESSAGE(STATUS "Gsl found at ${GSL_INCLUDEDIR}")
    SET(GSL_LIBRARIES ${GSL_LIBRARY_C})
	SET(GSL_INCLUDE_DIR ${GSL_INCLUDEDIR} ${GSL_INCLUDEDIR}/..)
    if (UNIX)
		SET(GSL_LIBRARIES ${GSL_LIBRARIES} m)
	endif()
	SET(gsl 1)
ELSE()
	MESSAGE(STATUS "Gsl not found.")
ENDIF()



