
include(FindPkgConfig)

pkg_check_modules(NETCDF QUIET)

if(NOT NETCDF_INCLUDEDIR AND NOT NETCDF_LIBRARIES)
	set(NETCDF_INCLUDEDIR NETCDF_INCLUDEDIR-NOTFOUND CACHE STRING "" FORCE)
	FIND_PATH(NETCDF_INCLUDEDIR netcdf.h
		HINTS
		ENV NETCDF_DIR
		PATH_SUFFIXES include
		PATHS
		~/Library/Frameworks
		/Library/Frameworks
		)
	FIND_LIBRARY(NETCDF_LIBRARY_C netcdf 
		HINTS
		ENV NETCDF_DIR
		PATH_SUFFIXES lib
		PATHS
		)
	FIND_LIBRARY(NETCDF_LIBRARY_CPP netcdf_c++
		HINTS
		ENV NETCDF_DIR
		PATH_SUFFIXES lib
		PATHS
		)
endif()

#message(STATUS "NETCDF: ${NETCDF_INCLUDEDIR}")
#message(STATUS "NETCDF: ${NETCDF_LIBRARY_C}")
#message(STATUS "NETCDF: ${NETCDF_LIBRARY_CPP}")
IF(NETCDF_INCLUDEDIR AND NETCDF_LIBRARY_C AND NETCDF_LIBRARY_CPP)
	MESSAGE(STATUS "Netcdf found at ${NETCDF_INCLUDEDIR}")
    SET(NETCDF_LIBRARIES ${NETCDF_LIBRARY_CPP} ${NETCDF_LIBRARY_C})
	SET(NETCDF_INCLUDE_DIR ${NETCDF_INCLUDEDIR})
	SET(netcdf 1)
ELSE()
	MESSAGE(STATUS "Netcdf not found.")
ENDIF()



