
include(FindPkgConfig)

pkg_check_modules(GETDATA QUIET getdata>=0.6.0)
#message(STATUS "GD inc: ${GETDATA_INCLUDEDIR}")
#message(STATUS "GD libs: ${GETDATA_LIBRARIES}")

# FIXME: GETDATA_INCLUDEDIR AND GETDATA_LIBRARIES are set by pkg_check_modules, but
# GETDATA_LIBRARY_C and GETDATA_LIBRARY_CPP are not.
# Ubuntu: maybe /usr/local/lib/pkgconfig/getdata.pc is not correct
if(GETDATA_LIBRARIES AND NOT GETDATA_LIBRARY_CPP)
	set(GETDATA_LIBRARY_C ${GETDATA_LIBRARIES})
	set(GETDATA_LIBRARY_CPP ${GETDATA_LIBRARIES}++)
endif()


if(NOT GETDATA_INCLUDEDIR AND NOT GETDATA_LIBRARIES)
	set(GETDATA_INCLUDEDIR GETDATA_INCLUDEDIR-NOTFOUND CACHE STRING "" FORCE)
	FIND_PATH(GETDATA_INCLUDEDIR getdata.h
		HINTS
		ENV GETDATA_DIR
		PATH_SUFFIXES include/getdata include
		PATHS
		)
	FIND_LIBRARY(GETDATA_LIBRARY_C getdata 
		HINTS
		ENV GETDATA_DIR
		PATH_SUFFIXES lib
		PATHS
		)
	FIND_LIBRARY(GETDATA_LIBRARY_CPP getdata++
		HINTS
		ENV GETDATA_DIR
		PATH_SUFFIXES lib
		PATHS
		)
endif()

#message(STATUS "GD: ${GETDATA_INCLUDEDIR}")
#message(STATUS "GD lib c: ${GETDATA_LIBRARY_C}")
#message(STATUS "GD lib c++: ${GETDATA_LIBRARY_CPP}")
IF(GETDATA_LIBRARY_C AND GETDATA_LIBRARY_CPP AND GETDATA_INCLUDEDIR)
	MESSAGE(STATUS "Getdata found at ${GETDATA_INCLUDEDIR}")
    SET(GETDATA_LIBRARIES ${GETDATA_LIBRARY_CPP} ${GETDATA_LIBRARY_C})
	SET(GETDATA_INCLUDE_DIR ${GETDATA_INCLUDEDIR})
    if (UNIX)
		SET(GETDATA_LIBRARIES ${GETDATA_LIBRARIES} m)
	endif()
	SET(getdata 1)
ELSE()
	MESSAGE(STATUS "Getdata not found.")
ENDIF()



