FIND_PATH(CFITSIO_INCLUDE_DIR fitsio.h /usr/include /usr/local/include)

FIND_LIBRARY(CFITSIO_LIBRARY NAMES cfitsio PATH /usr/lib /usr/local/lib) 

IF (CFITSIO_INCLUDE_DIR AND CFITSIO_LIBRARY)
   SET(CFITSIO_FOUND TRUE)
ENDIF (CFITSIO_INCLUDE_DIR AND CFITSIO_LIBRARY)

IF (CFITSIO_FOUND)
   IF (NOT Cfitsio_FIND_QUIETLY)
      MESSAGE(STATUS "Found cfitsio: ${CFITSIO_LIBRARY}")
   ENDIF (NOT Cfitsio_FIND_QUIETLY)
ELSE (CFITSIO_FOUND)
   IF (Cfitsio_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find cfitsio")
   ENDIF (Cfitsio_FIND_REQUIRED)
ENDIF (CFITSIO_FOUND)